### ISSUE TITLE
Extra HTML pages that are not needed

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/TradeIn#8]
You have these error pages in HTML/CSS
![ss](https://user-images.githubusercontent.com/43019810/99650063-a1cfb000-2a5d-11eb-851a-527404ebcfa0.PNG)

This should be taking care of on the back-end, not the front-end.
Usually is response.end() you can send an HTML text to display something to the user making these extra pages repetitive

**Comment by ahmad420** [comment]
we wanted to add a responsive server error page with a gif related to the issue. (will be added soon )
